# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
    groups:
      minor-npm-dependencies:
        # NPM: Only group minor and patch updates (we want to carefully review major updates)
        update-types: [minor, patch]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 30
    groups:
      minor-actions-dependencies:
        # GitHub Actions: Only group minor and patch updates (we want to carefully review major updates)
        update-types: [minor, patch]
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
    groups:
      minor-composer-dependencies:
        # Composer: Only group minor and patch updates (we want to carefully review major updates)
        update-types: [minor, patch]
  - package-ecosystem: "docker"
    directories:
      - "/docker/application"
    schedule:
      interval: monthly
    cooldown:
      default-days: 30
  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 30
    ignore:
      # Error: The updater encountered one or more errors.
      - dependency-name: "stoplight/prism"
